# This workflow will install Python dependencies, run tests, run linting, and test building docs
name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: public.ecr.aws/w5r9l1c8/swsoc-docker-lambda-base:latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e '.[test]'
    - name: Run tests
      run: pytest --pyargs hermes_core --cov hermes_core
      env:
        PLATFORM: 'docker'
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3